import type { PrismaClient } from "@prisma/client";

// 15 channels from RESEARCH.md §4 + PLAN §6-9.
// priority: primary | secondary | hold | avoid
// status: active | paused | hold

export const channels = [
  { key: "cold-email", name: "Cold Email (Smartlead)", priority: "primary", status: "active", role: "Volume top-of-funnel — FMCSA-sourced + Apollo enriched + 3-step personalized sequence", weeklyTarget: 2000, unit: "emails", costPerMonth: 94, expectedClients: "5/month from 5K sends @ 0.5% to close", benchmarks: "Reply 3-5% baseline, 18% with personalisation, ~0.5% to booked call", bestPractice: "8 mailboxes × 30/day = 240/day sustained. Spend 60-90 sec personalising per prospect (5× reply lift).", rules: "Smartlead Pro $94/mo; warmup 14-21 days before first send; SPF+DKIM+DMARC mandatory; unsubscribe in <10 business days.", sortOrder: 1 },
  { key: "linkedin-dm", name: "LinkedIn DM + Outbound", priority: "primary", status: "active", role: "Manual + Sales Nav — connection request → 4-step DM sequence with unprompted Loom on Day 7", weeklyTarget: 100, unit: "connects", costPerMonth: 0, expectedClients: "2/month + long-tail authority", benchmarks: "Acceptance 35-50% (throttle if <30%); ~8% DM reply post-accept", bestPractice: "20-25/day max manual. NEVER use HeyReach (banned Feb 2025). Dripify only at <25/day if at all.", rules: "Voice DM > text DM 3-5× reply rate. Surface 'Pakistan' identity early.", sortOrder: 2 },
  { key: "cold-call", name: "Cold Calling (OpenPhone)", priority: "primary", status: "active", role: "Underused, high-quality conversations — verified mobile direct-dial from FMCSA", weeklyTarget: 250, unit: "dials", costPerMonth: 19, expectedClients: "3/month from 1,000 dials", benchmarks: "Connect 18-22%, dial-to-meeting 2.3% avg / 5-8% top quartile, close 20-25% on trucking calls", bestPractice: "90 min/day for 50 dials. 30-sec opener: announce who you ARE NOT first.", rules: "Direct-dial mobile only; landlines waste time. Never bulk-cold-call this niche (research §1 prohibition).", sortOrder: 3 },
  { key: "past-clients", name: "Past-Client Re-Engagement", priority: "primary", status: "active", role: "#1 HIGHEST-ROI ACTIVITY per RESEARCH. Week 1 only, then quarterly value drop", weeklyTarget: 100, unit: "contacts", costPerMonth: 0, expectedClients: "2-3 closes + 5-10 referral leads in M1", benchmarks: "Warm reply 15-25%, reply→call 30%, call→close 40-50%", bestPractice: "Segment A (repeat 5★) / B (single 5★) / C (skip). A-tier gets custom 60-90s Loom within 14 days.", rules: "Referral incentive: $500/$500 two-way (referrer gets $500 cash, new client gets $500 off).", sortOrder: 4 },
  { key: "linkedin-content", name: "LinkedIn Loom Teardowns (Weekly)", priority: "primary", status: "active", role: "Compounding moat — 1 per week → 12 in 90d. The lead-magnet flywheel.", weeklyTarget: 1, unit: "teardowns", costPerMonth: 0, expectedClients: "Inbound flywheel + portfolio proof + DM enablement", benchmarks: "18-32% conversion as lead magnet; end-card CTA → call 15-25%", bestPractice: "4-min Loom. Real broken site. 3 specific failures. Post as native doc + Loom link + 3 FB groups.", rules: "NEVER post to Reddit (permaban). NEVER pitch in groups — value-only.", sortOrder: 5 },
  { key: "linkedin-posts", name: "LinkedIn Posts (4/wk)", priority: "primary", status: "active", role: "Foundation authority — Mon carousel / Wed video / Fri text / Sun case study", weeklyTarget: 4, unit: "posts", costPerMonth: 0, expectedClients: "1-3 inbound DMs/week after 60 days", benchmarks: "Posts with 1-3 hashtags avg 14.7 likes; compounding slow but high trust signal", bestPractice: "1-3 hashtags max. Hook in first 2 lines (mobile preview). Reply to every comment <1 hour.", rules: "No emojis-as-bullets. No 'team' language (founder voice only).", sortOrder: 6 },
  { key: "fiverr-upwork", name: "Fiverr / Upwork (Baseline Cash)", priority: "primary", status: "active", role: "$5-8K/mo baseline cashflow runway — keep active during agency build", weeklyTarget: 25, unit: "applications", costPerMonth: 0, expectedClients: "3-5/month (ongoing baseline)", benchmarks: "10-20% conversion on Upwork buyer-request applications", bestPractice: "Apply to 5-10 buyer requests/day. Optimize 3 logistics-specific gigs.", rules: "Don't quit until M3 retainer base is locked. Phase out only once $5K MRR is secure.", sortOrder: 7 },
  { key: "partnerships", name: "Factor / Insurance Partnerships", priority: "secondary", status: "active", role: "Long-term moat — setup Phase 2, compound from M2+", weeklyTarget: 5, unit: "outreach emails", costPerMonth: 0, expectedClients: "1-2 deals/partner/quarter after M3", benchmarks: "5-10% response rate to partnership pitch; high LTV", bestPractice: "Target factoring + insurance reps to small carriers. $500 per closed referral.", rules: "Long sales cycle — partners deliver in M3+, not M1.", sortOrder: 8 },
  { key: "facebook-groups", name: "Facebook Groups (Organic)", priority: "secondary", status: "active", role: "Value-first comments in 3-5 logistics groups; weekly free teardown post once trusted", weeklyTarget: 25, unit: "comments", costPerMonth: 0, expectedClients: "1-2 inbound DMs/week (slow compound)", benchmarks: "Low but cumulative; movers groups especially high-response", bestPractice: "9:1 rule — 9 helpful comments per 1 self-reference. Never link your site in answers.", rules: "Some groups ban any self-promo — read pinned rules.", sortOrder: 9 },
  { key: "click-to-whatsapp", name: "Click-to-WhatsApp (CTWA)", priority: "secondary", status: "hold", role: "UNIQUE OFFSHORE UNLOCK — async replies across time zones make Pakistan look 'fast'", weeklyTarget: 0, unit: "conversations", costPerMonth: 5, expectedClients: "Phase 2 / M2+ — needs CTWA ads to drive volume", benchmarks: "72-hr free messaging window; $0.025/msg after 1K free service convos/month", bestPractice: "Phase 1 M1: OpenPhone WhatsApp app, manual replies. Phase 2 M2+: GHL Lead Connector + CAPI.", rules: "Hold for ad launch Week 4 — paired with Meta CTWA ad.", sortOrder: 10 },
  { key: "meta-ads", name: "Meta Ads (Paid)", priority: "secondary", status: "hold", role: "Validation budget M1 ($300), scale to $1,200 by M3 — first paid close typically M3", weeklyTarget: 0, unit: "ad spend $", costPerMonth: 300, expectedClients: "M1: 0-1 close. M2: 0-1. M3: 2-4.", benchmarks: "Lead form CPL $8-25, booked call CPL $40-120, true cold B2B CPL $200-800", bestPractice: "$150 Meta lead form + $90 CTWA + $30 retargeting + $30 TikTok Spark", rules: "Don't say 'Guaranteed'/'Best'/'#1'/'Make money'/'FREE!' — Meta ban risk. No personal-attribute targeting.", sortOrder: 11 },
  { key: "tiktok-organic", name: "TikTok Organic", priority: "secondary", status: "hold", role: "Spark Ads boosting organic only — max 15-20% of ad spend", weeklyTarget: 1, unit: "post", costPerMonth: 30, expectedClients: "Awareness only, not primary client source M1-M3", benchmarks: "CPL $15-60; CTR 1.0-2.5%; CPM $8-18", bestPractice: "Only if 1K+ organic views — Spark Ad gets 134% higher completion vs cold paid.", rules: "Start Week 4 — first TikTok post Day 24.", sortOrder: 12 },
  { key: "google-search-ads", name: "Google Search Ads", priority: "hold", status: "hold", role: "M4+ play — too expensive in M1 to validate", weeklyTarget: 0, unit: "ad spend $", costPerMonth: 0, expectedClients: "Defer until M4 (CPL $200-800 in M1 too high)", benchmarks: "B2B logistics keywords: high intent, high CPC", bestPractice: "Don't run until messaging validated by organic.", rules: "M1 prohibition per RESEARCH §1.", sortOrder: 13 },
  { key: "podcast-guesting", name: "Podcast Guest Appearances", priority: "secondary", status: "hold", role: "High LTV-per-impression, slow to land — pitch M1 W3+, expect bookings M3+", weeklyTarget: 2, unit: "pitches", costPerMonth: 0, expectedClients: "1 booking/mo after ~8 pitches; 6 episodes/90d = compounding authority", benchmarks: "~1:10 hit rate on cold pitch", bestPractice: "Target Truck N' Hustle, Oakley Podcast, Ask The Trucker, WHAT THE TRUCK?!?", rules: "Angle: '800+ logistics websites — what every freight company gets wrong online.'", sortOrder: 14 },
  { key: "reddit", name: "Reddit (Intelligence Only)", priority: "hold", status: "hold", role: "Read threads only — NEVER pitch (permaban risk)", weeklyTarget: 0, unit: "intel reads", costPerMonth: 0, expectedClients: "Indirect — inform messaging from r/Truckers + r/Logistics threads", benchmarks: "n/a — info gathering", bestPractice: "Track 'I'm starting a trucking company, what website?' threads. Save copy patterns.", rules: "NEVER comment with self-link. NEVER pitch service. 9:1 rule if commenting helpfully.", sortOrder: 15 },
  { key: "newsletter-beehiiv", name: "Beehiiv Newsletter (M2 launch)", priority: "secondary", status: "hold", role: "Owned-audience moat — weekly Loom teardown + 3 tactical tips", weeklyTarget: 1, unit: "emails", costPerMonth: 0, expectedClients: "Compound moat — 50 subs by M3, 200 by M6", benchmarks: "25-40% B2B open rate; sticky but slow growth", bestPractice: "Repurpose weekly Loom + 3 tactical tips. Send to past clients + cold-email replies + connects.", rules: "M2+ launch (not M1). Free tier sufficient until 2K subs.", sortOrder: 16 },
];

export async function seedChannels(db: PrismaClient) {
  for (const c of channels) {
    await db.channel.create({ data: c });
  }
  console.log(`  ✓ Seeded ${channels.length} channels`);
}
